export type Language = 'en' | 'zh';

export const TRANSLATIONS = {
  en: {
    common: {
      loading: "Loading...",
      error: "Error",
      ask: "Ask",
      send: "Send",
      answer: "Answer",
    },
    home: {
      tagline: "AI-Powered Research Companion",
      title: "PaperLens",
      subtitle: "Transform dense academic PDFs into beautiful, interactive, and easy-to-read web experiences.",
      dropText: "Drop your PDF here",
      browseText: "or click to browse",
      analyzing: "Analyzing...",
      generate: "Generate Paper Site",
    },
    paper: {
      notFound: "Paper Not Found",
      redirecting: "Redirecting to upload page...",
      footer: "Generated by PaperLens • Vibe Coding MVP",
    },
    blocks: {
      badges: {
        confidence: "Confidence",
        formulas: "Formulas",
        experiments: "Has Experiments",
      },
      takeaways: {
        title: "Key Takeaways",
      },
      method: {
        title: "Methodology",
        steps: "Key Steps",
        components: "Core Components",
      },
      experiments: {
        title: "Experiments",
        datasets: "Datasets",
        baselines: "Baselines",
        results: "Key Results",
      },
      figures: {
        title: "Visual Guide",
        preview: "Figure Preview",
      },
      limitations: {
        title: "Limitations",
      },
      glossary: {
        title: "Glossary",
      },
      qa: {
        title: "Ask the Paper",
        subtitle: "Based on",
        placeholder: "Ask anything about this paper...",
        loading: "Thinking...",
      }
    }
  },
  zh: {
    common: {
      loading: "加载中...",
      error: "错误",
      ask: "提问",
      send: "发送",
      answer: "回答",
    },
    home: {
      tagline: "AI 驱动的科研伴侣",
      title: "PaperLens",
      subtitle: "将晦涩的学术论文转化为精美、互动且易读的网页体验。",
      dropText: "将 PDF 拖放到此处",
      browseText: "或点击浏览",
      analyzing: "正在分析...",
      generate: "生成论文网页",
    },
    paper: {
      notFound: "未找到论文",
      redirecting: "正在重定向到上传页面...",
      footer: "由 PaperLens 生成 • Vibe Coding MVP",
    },
    blocks: {
      badges: {
        confidence: "置信度",
        formulas: "公式密度",
        experiments: "包含实验",
      },
      takeaways: {
        title: "核心要点",
      },
      method: {
        title: "研究方法",
        steps: "关键步骤",
        components: "核心组件",
      },
      experiments: {
        title: "实验分析",
        datasets: "数据集",
        baselines: "基线模型",
        results: "关键结果",
      },
      figures: {
        title: "图表导读",
        preview: "图表预览",
      },
      limitations: {
        title: "局限性",
      },
      glossary: {
        title: "术语表",
      },
      qa: {
        title: "向论文提问",
        subtitle: "基于",
        placeholder: "关于这篇论文的任何问题...",
        loading: "思考中...",
      }
    }
  }
};
